#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  install-agent-proxy-config.sh [options]

Configure server-side Claude Code and/or Codex to use a ccrp SSH reverse proxy.
Run this script on the server, not on your local machine.

Options:
  --target claude|codex|both      Which client config to write (default: both)
  --base-url URL                  Shared reverse proxy URL (default: http://127.0.0.1:18080)
  --anthropic-base-url URL        Claude Code base URL (default: --base-url)
  --openai-base-url URL           Codex OpenAI-compatible base URL (default: --base-url + /v1)
  --token TOKEN                   Optional proxy/API token
  --token-env NAME                Environment variable name to read token from on the server
  --model MODEL                   Model name for both clients
  --claude-model MODEL            Claude Code model name override
  --codex-model MODEL             Codex model name override
  --codex-provider NAME           Codex model provider id (default: ccrp)
  --codex-wire-api chat|responses Codex wire API (default: chat; most OpenAI-compatible proxies use chat)
  --no-set-default                Add Codex provider but do not make it the default provider
  --dry-run                       Print actions without writing files
  -h, --help                      Show this help

Examples:
  # Private ccrp tunnel on the server: http://127.0.0.1:18080
  ./install-agent-proxy-config.sh --target both --base-url http://127.0.0.1:18080

  # If your proxy requires a token
  ./install-agent-proxy-config.sh --target both --base-url http://127.0.0.1:18080 --token-env CCRP_TOKEN

  # Claude Code only
  ./install-agent-proxy-config.sh --target claude --base-url http://127.0.0.1:18080 --claude-model claude-sonnet-4-5

  # Codex only, OpenAI-compatible /v1 endpoint
  ./install-agent-proxy-config.sh --target codex --openai-base-url http://127.0.0.1:18080/v1 --codex-model gpt-5-codex
EOF
}

TARGET="both"
BASE_URL="http://127.0.0.1:18080"
ANTHROPIC_BASE_URL=""
OPENAI_BASE_URL=""
TOKEN=""
TOKEN_ENV=""
MODEL=""
CLAUDE_MODEL=""
CODEX_MODEL=""
CODEX_PROVIDER="ccrp"
CODEX_WIRE_API="chat"
SET_DEFAULT=1
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET="${2:?missing value for --target}"; shift 2 ;;
    --base-url) BASE_URL="${2:?missing value for --base-url}"; shift 2 ;;
    --anthropic-base-url) ANTHROPIC_BASE_URL="${2:?missing value for --anthropic-base-url}"; shift 2 ;;
    --openai-base-url) OPENAI_BASE_URL="${2:?missing value for --openai-base-url}"; shift 2 ;;
    --token) TOKEN="${2:?missing value for --token}"; shift 2 ;;
    --token-env) TOKEN_ENV="${2:?missing value for --token-env}"; shift 2 ;;
    --model) MODEL="${2:?missing value for --model}"; shift 2 ;;
    --claude-model) CLAUDE_MODEL="${2:?missing value for --claude-model}"; shift 2 ;;
    --codex-model) CODEX_MODEL="${2:?missing value for --codex-model}"; shift 2 ;;
    --codex-provider) CODEX_PROVIDER="${2:?missing value for --codex-provider}"; shift 2 ;;
    --codex-wire-api) CODEX_WIRE_API="${2:?missing value for --codex-wire-api}"; shift 2 ;;
    --no-set-default) SET_DEFAULT=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

case "$TARGET" in
  claude|codex|both) ;;
  *) echo "--target must be claude, codex, or both" >&2; exit 2 ;;
esac

case "$CODEX_WIRE_API" in
  chat|responses) ;;
  *) echo "--codex-wire-api must be chat or responses" >&2; exit 2 ;;
esac

trim_trailing_slash() {
  local value="$1"
  while [[ "$value" == */ ]]; do value="${value%/}"; done
  printf '%s' "$value"
}

BASE_URL="$(trim_trailing_slash "$BASE_URL")"
ANTHROPIC_BASE_URL="$(trim_trailing_slash "${ANTHROPIC_BASE_URL:-$BASE_URL}")"
OPENAI_BASE_URL="$(trim_trailing_slash "${OPENAI_BASE_URL:-$BASE_URL/v1}")"
CLAUDE_MODEL="${CLAUDE_MODEL:-$MODEL}"
CODEX_MODEL="${CODEX_MODEL:-$MODEL}"

if [[ -n "$TOKEN_ENV" && -z "$TOKEN" ]]; then
  TOKEN="${!TOKEN_ENV:-}"
  if [[ -z "$TOKEN" ]]; then
    echo "Warning: --token-env $TOKEN_ENV is not set in the current shell; config will reference the env var but wrappers will not embed a token." >&2
  fi
fi

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
CCRP_CONFIG_DIR="$CONFIG_HOME/ccrp"
ENV_FILE="$CCRP_CONFIG_DIR/agent-proxy.env"
CLAUDE_SETTINGS="${CLAUDE_SETTINGS:-$HOME/.claude/settings.json}"
CODEX_CONFIG="${CODEX_HOME:-$HOME/.codex}/config.toml"
CODEX_ENV="${CODEX_HOME:-$HOME/.codex}/.env"
LOCAL_BIN="$HOME/.local/bin"

run_or_echo() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run] %s\n' "$*"
  else
    "$@"
  fi
}

write_env_file() {
  run_or_echo mkdir -p "$CCRP_CONFIG_DIR"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[dry-run] write $ENV_FILE"
    return
  fi
  umask 077
  {
    echo '# Generated by SSHRev ccrp install-agent-proxy-config.sh'
    printf 'export CCRP_BASE_URL=%q\n' "$BASE_URL"
    printf 'export ANTHROPIC_BASE_URL=%q\n' "$ANTHROPIC_BASE_URL"
    printf 'export OPENAI_BASE_URL=%q\n' "$OPENAI_BASE_URL"
    if [[ -n "$TOKEN_ENV" ]]; then
      printf 'export CCRP_TOKEN="${%s:-}"\n' "$TOKEN_ENV"
    elif [[ -n "$TOKEN" ]]; then
      printf 'export CCRP_TOKEN=%q\n' "$TOKEN"
    else
      echo 'export CCRP_TOKEN=""'
    fi
    echo 'if [ -n "${CCRP_TOKEN:-}" ]; then'
    echo '  export ANTHROPIC_AUTH_TOKEN="$CCRP_TOKEN"'
    echo '  export OPENAI_API_KEY="$CCRP_TOKEN"'
    echo 'else'
    echo '  export OPENAI_API_KEY="ccrp"'
    echo 'fi'
    if [[ -n "$CLAUDE_MODEL" ]]; then printf 'export ANTHROPIC_MODEL=%q\n' "$CLAUDE_MODEL"; fi
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

configure_claude() {
  run_or_echo mkdir -p "$(dirname "$CLAUDE_SETTINGS")"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[dry-run] merge Claude Code env into $CLAUDE_SETTINGS"
    return
  fi
  python3 - "$CLAUDE_SETTINGS" "$ANTHROPIC_BASE_URL" "$TOKEN_ENV" "$TOKEN" "$CLAUDE_MODEL" <<'PY'
import json
import os
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
base_url, token_env, token, model = sys.argv[2:6]
if path.exists():
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
        if not isinstance(data, dict):
            data = {}
    except json.JSONDecodeError:
        backup = path.with_suffix(path.suffix + ".bak")
        backup.write_text(path.read_text(encoding="utf-8", errors="replace"), encoding="utf-8")
        data = {}
else:
    data = {}

env = data.setdefault("env", {})
if not isinstance(env, dict):
    env = {}
    data["env"] = env

env["ANTHROPIC_BASE_URL"] = base_url
if token_env:
    env["ANTHROPIC_AUTH_TOKEN"] = "${" + token_env + "}"
elif token:
    env["ANTHROPIC_AUTH_TOKEN"] = token
else:
    env.pop("ANTHROPIC_AUTH_TOKEN", None)
if model:
    env["ANTHROPIC_MODEL"] = model

path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY
}

configure_codex() {
  run_or_echo mkdir -p "$(dirname "$CODEX_CONFIG")"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[dry-run] merge Codex provider into $CODEX_CONFIG"
    echo "[dry-run] write $CODEX_ENV"
    return
  fi
  python3 - "$CODEX_CONFIG" "$CODEX_PROVIDER" "$OPENAI_BASE_URL" "$CODEX_WIRE_API" "$CODEX_MODEL" "$SET_DEFAULT" <<'PY'
import pathlib
import re
import sys
import time

path = pathlib.Path(sys.argv[1])
provider, base_url, wire_api, model, set_default = sys.argv[2:7]
set_default = set_default == "1"
text = path.read_text(encoding="utf-8-sig") if path.exists() else ""
if text:
    backup = path.with_name(path.name + ".bak." + time.strftime("%Y%m%d%H%M%S"))
    backup.write_text(text, encoding="utf-8")
text = re.sub(r"(?ms)^# >>> ccrp agent proxy\n.*?^# <<< ccrp agent proxy\n?", "", text).strip() + "\n"

root_lines = []
rest_lines = []
in_root = True
for line in text.splitlines():
    if in_root and line.lstrip().startswith("["):
        in_root = False
    if in_root:
        if set_default and re.match(r"\s*(model_provider|model)\s*=", line):
            continue
        root_lines.append(line)
    else:
        rest_lines.append(line)

if set_default:
    default_lines = [
        "# >>> ccrp agent proxy defaults",
        f'model_provider = "{provider}"',
    ]
    if model:
        default_lines.append(f'model = "{model}"')
    default_lines.append("# <<< ccrp agent proxy defaults")
    root = "\n".join(default_lines + [""] + [line for line in root_lines if line.strip()])
else:
    root = "\n".join(root_lines).strip()

provider_block = "\n".join([
    "# >>> ccrp agent proxy",
    f"[model_providers.{provider}]",
    f'name = "{provider}"',
    f'base_url = "{base_url}"',
    'env_key = "OPENAI_API_KEY"',
    f'wire_api = "{wire_api}"',
    "# <<< ccrp agent proxy",
])

parts = [part for part in [root.strip(), "\n".join(rest_lines).strip(), provider_block] if part]
path.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
PY
  umask 077
  {
    echo '# Generated by SSHRev ccrp install-agent-proxy-config.sh'
    printf 'OPENAI_BASE_URL=%s\n' "$OPENAI_BASE_URL"
    if [[ -n "$TOKEN_ENV" ]]; then
      printf 'OPENAI_API_KEY=${%s:-ccrp}\n' "$TOKEN_ENV"
    elif [[ -n "$TOKEN" ]]; then
      printf 'OPENAI_API_KEY=%s\n' "$TOKEN"
    else
      echo 'OPENAI_API_KEY=ccrp'
    fi
  } > "$CODEX_ENV"
  chmod 600 "$CODEX_ENV"
}

write_wrappers() {
  run_or_echo mkdir -p "$LOCAL_BIN"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[dry-run] write $LOCAL_BIN/claude-ccrp and $LOCAL_BIN/codex-ccrp"
    return
  fi
  cat > "$LOCAL_BIN/claude-ccrp" <<EOF
#!/usr/bin/env bash
set -euo pipefail
source "$ENV_FILE"
exec claude "\$@"
EOF
  cat > "$LOCAL_BIN/codex-ccrp" <<EOF
#!/usr/bin/env bash
set -euo pipefail
source "$ENV_FILE"
exec codex "\$@"
EOF
  chmod 700 "$LOCAL_BIN/claude-ccrp" "$LOCAL_BIN/codex-ccrp"
}

write_env_file
case "$TARGET" in
  claude) configure_claude ;;
  codex) configure_codex ;;
  both) configure_claude; configure_codex ;;
esac
write_wrappers

cat <<EOF
Done.

Base URLs:
  Claude Code: $ANTHROPIC_BASE_URL
  Codex:       $OPENAI_BASE_URL

Generated files:
  $ENV_FILE
  $LOCAL_BIN/claude-ccrp
  $LOCAL_BIN/codex-ccrp
EOF

if [[ "$TARGET" == "claude" || "$TARGET" == "both" ]]; then
  echo "  $CLAUDE_SETTINGS"
fi
if [[ "$TARGET" == "codex" || "$TARGET" == "both" ]]; then
  echo "  $CODEX_CONFIG"
  echo "  $CODEX_ENV"
fi

cat <<'EOF'

Next:
  1. Make sure the ccrp SSH reverse tunnel is running from your local machine.
  2. On the server, verify the proxy: curl http://127.0.0.1:18080
  3. Start clients with: claude-ccrp or codex-ccrp
EOF
